# vim: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - container_name is defined
      - image_name is defined
      - volumes is defined

- name: docker image is present
  docker_image:
    name: "{{ image_name }}"
    path: "{{ role_path + '/files/' + src }}"
    state: present

- name: docker container is started
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    volumes: "{{ volumes|default([]) }}"
    state: started
    recreate: "{{ recreate|default(false) }}"

- name: add containers to inventory
  changed_when: false
  add_host:
    groups: testnodes
    name: "{{ container_name }}"
    ansible_connection: docker
