# vim: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - container_name is defined
      - image_name is defined
      - src is defined

- debug: var=member_of_groups|default(['testnodes'])
  tags:
    - never
    - debug

- name: docker image {{ image_name }} is present
  docker_image:
    name: "{{ image_name }}"
    path: "{{ role_path + '/files/' + src }}"
    state: present

- name: docker container {{ container_name }} is started
  docker_container:
    name: "{{ container_name }}"
    image: "{{ image_name }}"
    volumes: "{{ volumes|default([]) }}"
    state: started
    recreate: "{{ recreate|default(false) }}"

- name: add container {{ container_name }} to inventory
  changed_when: false
  add_host:
    groups: "{{ member_of_groups|default(['testnodes']) }}"
    name: "{{ container_name }}"
    ansible_connection: docker
