---
sudo: required
dist: xenial
language: minimal
before_install:
  - sudo apt-add-repository --yes ppa:ansible/ansible-2.7 && sudo apt-get update
  - sudo apt-get install ansible
  - dpkg -l
  - export ANSIBLE_CI_BRANCH=$TRAVIS_BRANCH
  - sudo ln -s $TRAVIS_BUILD_DIR /etc/ansible/roles/ansible_CI
  - ansible-playbook -b -D before_install.yml -t all,debug
install:
script:
  - ansible-playbook -D tests/test.yml    -t all,debug
