# vim: set ft=yaml ts=2:
---

sudo: required
dist: xenial
language: minimal
env:
  global:
    - ANSIBLE_ROLE_NAME=mafalb.ansible_ci
    - CI=travis
    - ANSIBLE_FORCE_COLOR=1
  matrix:
    - targeted_ansible_version: 2.7

before_install:
  - export ANSIBLE_CI_BRANCH=$TRAVIS_BRANCH CI_BUILD_DIR=$TRAVIS_BUILD_DIR
  - sudo apt-add-repository --yes ppa:ansible/ansible-${targeted_ansible_version} && sudo apt-get update
  - sudo apt-get install ansible
  - sudo pip install docker
  - dpkg -l
  - pip list
  - ansible --version
  - ansible localhost -m setup
  - ansible-playbook -b -D -t all,debug before_install.yml
  - ls -lR roles
install:
  - ansible-playbook -b -D -t all,debug install.yml
script:
  - ansible-playbook -D -t all,debug tests/test.yml
  - ansible-playbook -D -t all,debug tests/test.yml | tee /tmp/idempotence.tee
  - "! grep -E 'ok=.*changed=[^0].*unreachable=.*failed=' /tmp/idempotence.tee"
after_script:
  - pip list
