# vim: set ft=yaml ts=2:
---

sudo: required
dist: xenial
language: minimal
env:
  - targeted_ansible_version: 2.7

before_install:
  - sudo apt-add-repository --yes ppa:ansible/ansible-${targeted_ansible_version} && sudo apt-get update
  - sudo apt-get install ansible
  - dpkg -l
  - export ANSIBLE_CI_BRANCH=$TRAVIS_BRANCH
  - export CI_BUILD_DIR=$TRAVIS_BUILD_DIR
  - sudo ln -s $TRAVIS_BUILD_DIR /etc/ansible/roles/mafalb.ansible_ci
  - ls -lR /etc/ansible/roles
  - ls -lR tests/
  - ansible --version
  - ansible localhost -m setup
  - ansible-playbook -b -D -t all,debug before_install.yml
install:
  - ansible-playbook -b -D -t all,debug install.yml
script:
  - ansible-playbook -D -t all,debug tests/test.yml
  - >
    ansible-playbook -D -t all,debug tests/test.yml
    |grep 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
