# vi: set ft=yaml ts=2:
---


- hosts: cihost
  tasks:
    - name: directory for roles does exist
      file:
        path: "{{ {{ ansible_env.CI_BUILD_DIR }}/roles }}"
        state: directory

    - name: symlink to CI_BUILD_DIR does exist
      file:
        src: "{{ ansible_env.CI_BUILD_DIR }}"
        dest: "{{ ansible_env.CI_BUILD_DIR }}/roles/{{ ansible_env.ANSIBLE_ROLE_NAME }}"
        state: link

    - name: ansible.cfg does exist
      template:
        src: ansible.cfg.j2
        dest: "{{ ansible_env.CI_BUILD_DIR }}/ansible.cfg"
        backup: true

    - name: inventory file does exist
      copy:
        content: |
          cihost ansible_connection=local
        dest: "{{ ansible_env.CI_BUILD_DIR }}/hosts"
...
