# vi: set ft=yaml ts=2:
---


- hosts: localhost
  tasks:
    - name: directory for roles does exist
      file:
        path: roles
        state: directory

    - name: symlink to CI_BUILD_DIR does exist
      file:
        src: "{{ ansible_env.CI_BUILD_DIR }}"
        dest: roles/{{ ansible_env.ANSIBLE_ROLE_NAME }}
        state: link

- hosts: localhost
  roles:
    - role: mafalb.ansible_ci

...
