# vi: set ft=yaml ts=2:
---

- hosts: localhost
  vars:
    - docker_assume_already_installed: true
  roles:
    - role: mafalb.ansible/control_machine
    - role: mafalb.ansible/node
    - role: mafalb.docker/daemon
    - role: mafalb.docker/ansible
  tasks:
    - name: get the docker version
      check_mode: false
      command: docker version
      register: _docker
    - debug: var=ansible_env
    - debug: var=_dpkg
    - debug: var=_docker

...
