# vi: set ft=yaml ts=2:
---

- name: mafalb.ansible-ansible
  src: https://github.com/mafalb/ansible-ansible
  version: origin/dev

- name: mafalb.docker
  src: https://github.com/mafalb/ansible-docker
  version: origin/dev

- name: mafalb.ansible-ansible_ci
  src: https://github.com/mafalb/ansible-ansible_ci
  version: origin/dev

...
