# vi: set ft=yaml ts=2:
---

- name: assertions
  assert:
    that:
      - ansible_env.ANSIBLE_CI_BRANCH is defined

- name: write requirements.yml
  template:
    src: requirements.yml.j2
    dest: "{{ role_path }}/../requirements.yml"
