# vi: set ft=yaml ts=2:
---

- name: ansible.cfg does exist
  template:
    src: ansible.cfg.j2
    dest: /etc/ansible
    backup: true

- name: install requirements
  check_mode: false
  command: ansible-galaxy install -r {{ role_path }}/requirements.yml -p /etc/ansible/roles
