# vim: set ft=yaml ts=2:
---

- name: get the docker version
  check_mode: false
  changed_when: false
  command: docker version
  register: _docker

- debug: var=ansible_env
- debug: var=_dpkg
- debug: var=_docker

...
